<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "contentpack"
 *
 * Auto generated by Extension Builder 2019-10-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'iTechnology Content Pack',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Eike Lars Henke',
    'author_email' => 'eike.henke@itechnology.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
